#!/bin/bash
x=`ps aux | grep "compton --transparency-color-filter" | wc -l`
if [ $x -gt 1 ]; then 
	exit 0
fi
killall compton
cd /home/nitroglycerine/Downloads/compton/myclone/compton/ && \
/home/nitroglycerine/Downloads/compton/myclone/compton/compton --transparency-color-filter -b
